### ISSUE TITLE
太平通还能跑起来吗，报错，没写变量直接跑也报错

### ISSUE THREAD

**Issue by thisThink** [xiaobu689/HhhhScripts#3]
![image](https://github.com/user-attachments/assets/f652e3b0-d94b-433e-b91b-ac429d234dd3)
![image](https://github.com/user-attachments/assets/a923b5f9-1fde-466d-beef-5aba126ad25b)

**Comment by xiaobu689** [comment]
正常跑，你的报错目测变量格式不对，重新检查下

**Comment by xiaobu689** [comment]
> > 运行正常，您报错的项目测量指标格式正确，重新检查下
> 
> 没玩明白，青龙变量TaiPingTong，值是抓包x-ac-token-ticket的值，换了两个青龙，都报错。。。

[
    {
        "token": "xxxx",
        "userId": "随意"
    }

**Comment by xiaobu689** [comment]
> > 运行正常，您报错的项目测量指标格式正确，重新检查下
> 
> 没玩明白，青龙变量TaiPingTong，值是抓包x-ac-token-ticket的值，换了两个青龙，都报错。。。

[
{
"token": "xxxx",
"userId": "随意"
}
]

**Comment by thisThink** [comment]
> > 没玩明白，青龙变量TaiPingTong，值是抓包x-ac-token-ticket的值，换了两个青龙，都报错。。。
