### ISSUE TITLE
上海系的脚本G了吗

### ISSUE THREAD

**Issue by ZhangQing3411** [xiaobu689/HhhhScripts#5]
上海系的脚本按要求抓的token，脚本运行错误：上海宝山共获取到1个账号

======== ▷ 第 1 个账号 ◁ ========
Traceback (most recent call last):
  File "/ql/data/scripts/xiaobu689_HhhhScripts_main/上海宝山.py", line 264, in <module>
    SHBS(account_info).main()
  File "/ql/data/scripts/xiaobu689_HhhhScripts_main/上海宝山.py", line 27, in __init__
    self.isComment = account_info.split('#')[1]
IndexError: list index out of range
都是报同样的问题。

**Comment by xiaobu689** [comment]
> 上海系的脚本按要求抓的token，脚本运行错误：上海宝山共获取到1个账号
> 
> ======== ▷ 第 1 个账号 ◁ ======== Traceback (most recent call last): File "/ql/data/scripts/xiaobu689_HhhhScripts_main/上海宝山.py", line 264, in SHBS(account_info).main() File "/ql/data/scripts/xiaobu689_HhhhScripts_main/上海宝山.py", line 27, in **init** self.isComment = account_info.split('#')[1] IndexError: list index out of range 都是报同样的问题。
没G， 变量格式：token#0

**Comment by ZhangQing3411** [comment]
token#0，这个0是指账号名称？

**Comment by ZhangQing3411** [comment]
OK了
