### ISSUE TITLE
去除代理后 报错

### ISSUE THREAD

**Issue by donotcareme** [xiaobu689/HhhhScripts#8]
xxxxxxxxxxxx
Traceback (most recent call last):
  File "/ql/data/scripts/ahhh/顺义抢兑.py", line 132, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/ql/data/scripts/ahhh/顺义抢兑.py", line 90, in main
    auth, phone, millisecond = token.split('#')
ValueError: not enough values to unpack (expected 3, got 1)
token按照要求填写的

**Comment by xiaobu689** [comment]
> xxxxxxxxxxxx Traceback (most recent call last): File "/ql/data/scripts/ahhh/顺义抢兑.py", line 132, in asyncio.run(main()) File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete return future.result() File "/ql/data/scripts/ahhh/顺义抢兑.py", line 90, in main auth, phone, millisecond = token.split('#') ValueError: not enough values to unpack (expected 3, got 1) token按照要求填写的

变量格式：token1#phone1#毫秒数， 多账号用&连接， 我本子里忘了写了

**Comment by donotcareme** [comment]
谢谢哥
